# ref: https://github.com/crazy-max/diun/blob/master/.github/workflows/build.yml

name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.3.0
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/bake-action@master
      with:
        push: true
        targets: image-all
